In [1]:
import numpy as np

b = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(b.size)
print(b.shape)

9
(3, 3)


In [4]:
print(b.dtype)

int64


In [5]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
c = a+b

print(c)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [6]:
c = c.transpose()
print(c)

[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
